# GitHub Pages Configuration for Cipher
title: "Cipher - End-to-End Encrypted P2P Social Network"
description: "A zero-knowledge, end-to-end encrypted peer-to-peer social network built with Rails. Share posts, images, and media with complete privacy."
author: "Cipher Team"
url: "https://your-username.github.io"
baseurl: "/cipher"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# SEO settings
twitter:
  username: cipher_p2p
  card: summary_large_image

facebook:
  app_id: 
  publisher: 

social:
  name: Cipher
  links:
    - https://github.com/your-username/cipher

# Google Analytics (optional)
google_analytics: 

# Theme
theme: minima